% This file contains the revision history of Data_Management folder of our
% tools.
% Current version of tools is "Data_Management v3.0.0"

hist_DataMgt(1).ver = '1.0.0';
hist_DataMgt(1).log = 'Initial Release';
hist_DataMgt(1).date = '30-Sep-2014';

hist_DataMgt(2).ver = '1.1.0';
hist_DataMgt(2).log = '1)Cleaned up ReqdResolution among several classes. Removed from all but OpSignal, renamed TestTolerance.  2)Removed CoderInfo lines from String methods to clean up data dictionaries.  3. Added HPF32KSV_Str.m';
hist_DataMgt(2).date = '28-Oct-2014';

hist_DataMgt(3).ver = '2.0.0';
hist_DataMgt(3).log = '1)HPF32KSV_Str.m bug fix.  2)OpSignal bug fix.  3)VerifyDD, two bug fixes.  4)New enumerations: ManufModeType, NVM_RequestResultType, Rte_ModeType_StaMd_Mode.  5) Changes made to how the EngVal, EngInit, EngMin and EngMax are changed. 6) Changes to the .dt classes to be compatable with changes made in 5).';
hist_DataMgt(3).date = '04-Feb-2015';

hist_DataMgt(4).ver = '2.1.0';
hist_DataMgt(4).log = '1)Fix to the dt.DiagSettings_Str';
hist_DataMgt(4).date = '04-Feb-2015';

hist_DataMgt(5).ver = '2.2.0';
hist_DataMgt(5).log = '1)Change to DataDict.IpSignal to prevent warnings when running a data dictionary. 2)dt.DiagSettings_Str fixed so that ''Threshold'' field is created. 3) Bug fix in enumeration class def of MotQuad1. 4) Fixed misspelling in FDD class. 5)Created EA3 and EA4 folders for structs and enums. 6) Add new enums and structs for EA4 and EA3. 7)Bug fixes in bt.uint32 and bt.sint32. 8) Fixed Val2String and MinMax2String functions to handle enums. 9) Bug fixes in VerifyDD.';
hist_DataMgt(5).date = '11-Feb-2015';

hist_DataMgt(6).ver = '2.3.0';
hist_DataMgt(6).log = '1)Bug fix in structEA3.HPF32KSV_Str. 2)Added enumerations for NTC Status and NTC Number. 3) Fixed bug in bt.struct. 4) Bug Fix MotPrmNomEolRec1. 5) Added FilLpRec1 and FilHpRec1 structures. 6) Removed Owner property from FDD String method, and made the Owner.set method assign Owner to ''. 7)Updated constructor method for DataDict.SrvRunnable and DataDict.Client. 8)Bug Fixes in VerifyDD. 9)New EA3 enum AssistLmtFunc_Scom.';
hist_DataMgt(6).date = '17-Feb-2015';

hist_DataMgt(7).ver = '2.4.0';
hist_DataMgt(7).log = '1)Added StrtUpSt1 Enumeration. 2)Added NtcInfoRec1 structure. 3)Added ArbnQly1 enumeration. 4)Bug fix in EA3 SigQlfr1 enumeration. 5)Fixed bug in SysSt enum definition. 6)Change to CreateDD to improve data dictionary useablity.';
hist_DataMgt(7).date = '26-Feb-2015';

hist_DataMgt(8).ver = '2.5.0';
hist_DataMgt(8).log = '1)Added new DataDict class ConfigParam. 2)Bug fixes in DataDict.PIM and DataDict.NVM to update EngInit correctly. 3)Fixed bugs in MinMax2String and Val2String and changed rounding behavior. 4) Added enums LoaSt1 and LOA_State. 5) Improvements and more robustness added to VerifyDD.';
hist_DataMgt(8).date = '03-Mar-2015';

hist_DataMgt(9).ver = '2.6.0';
hist_DataMgt(9).log = ['1) Bug fixes in DataDict.Display, DataDict.PIM and DataDict.NVM.'...
    '2) Added Define and Header properties to DataDict.Constant class, updated string method for this class and DataDict.ConfigParams class.'...
    '3) Bug fixes in LoaSt and LOA_State enums.'...
    '4) In FDD class, Ntc property updated to have Debounce type property'...
    '5) Base types bt.uint8, bt.uint16, bt.uint32, bt.sint8, bt.sint16 and bt.sint32 were updated to allow for no input arguments.'...
    '6) CSReturn class was created to allow a return type to be defined for SrvRunnable and Client .Return properties.'...
    '7) The Client and SrvRunnable classes were updated to work with the new CSReturn class. Backward compatability was retained.'...
    '8) Common function Val2String was updated to accept inputs of strings and empty arrays.'...
    '9) CheckLongName routine modified.'...
    '10)New EA3 NTC numbers for LoaMgr'...
    '11)Updated VerifyDD tool for ConfigConst & SrvRunnables classes, Naming checks improved, bug fix for model parsing.'...
    '12)Added additional acceptable values for the CSArguments.Direction property.'];
hist_DataMgt(9).date = '23-Mar-2015';

hist_DataMgt(10).ver =  '2.7.0';
hist_DataMgt(10).log =  ['1) Bug fixes in VerifyDD tool for Constant Name & Unit Check, Model parsing method, DD .m file parsing, Error handling notifications'...
    '2) Added new property InitRowCol for DataDict.CSArguments, DataDict.Display, DataDict.PIM and DataDict.NVM classes for supporting Array of zeros as their Intial values for EA4 programs.'];
hist_DataMgt(10).date = '31-Mar-2015';

hist_DataMgt(11).ver =  '2.8.0';
hist_DataMgt(11).log =  '1) Bug fix for parsing an Data Dictionary file. 2) Changed DataDict.SrvRunnable and DataDict.Client to not force at least on CSArgument.';
hist_DataMgt(11).date = '07-Apr-2015';

hist_DataMgt(12).ver =  '2.9.0';
hist_DataMgt(12).log =  '1) Addition of enum.StrtUpSt2, enum.MotCurrEolCalSt2, struct.MotCtrlFromTwoMilliSecRec1, struct.MotCtrlToTwoMilliSecRec1, struct.TwoMilliSecFromMotCtrlRec1, struct.TwoMilliSecToMotCtrlRec1, struct.NtcInfoRec1, struct.NtcFltInfoRec1 and dt.s15p16.';
hist_DataMgt(12).date = '16-Apr-2015';

hist_DataMgt(13).ver =  '2.10.0';
hist_DataMgt(13).log =  ['1) Added logic to automatically update Header file information under CoderInfo Property based on .Header value.'...
                         '2) VerifyDD tool has been updated with enhanced logic for CSReturn class, Bug fix for PIM class, New check for Constant class, Safety Property check has been turned off for all classes except FDD class.'...
                         '3) Safety Rating has been turned off for all classes excpt FDD class till we develop a robust ASIL management process.'...
                         '4) Added logic to handle empty structures in bt.struct data class.'];
hist_DataMgt(13).date = '20-Apr-2015';

hist_DataMgt(14).ver =  '2.11.0';
hist_DataMgt(14).log =  '1) Bug fixes in VerifyDD. 2) CreateDD updated to suppor batch operations. 3) Bug fix in MotPrmNomEolRec1, no functional change to datatype information. 4) EngInit property was added back into DataDict.NVM data class.';
hist_DataMgt(14).date = '29-Apr-2015';

hist_DataMgt(15).ver =  '2.12.0';
hist_DataMgt(15).log =  ['1) VerifyDD --> Updated for ensuring Display, PIM, NTC variables used in DD & Model match each other.'...
                         '2) VerifyDD --> Updated Naming check for NVMs, PIMs, Constants, ConfigParams as per new EA4 Naming convention document.'...
                         '3) VerifyDD --> ModelDDTest subroutine for finding Display & PIM blocks in FDD model.'...
                         '4) VerifyDD --> Updated the allowable legal range of EngMax to 2^32.'...
                         '5) VerifyDD --> Turned-off .EngInit property check for PIM data class'...
                         '6) Data Types --> Added new Data Types "s18p13","u13p19" and removed "u21p19".'...
                         '7) Data Classes --> Bug fixes for "Struct" Datatype class, NVM & PIM Data class.'...
                         '8) EA3 Enums --> Bug fix for "AssistLmtFunc_Scom".'...
                         '9) EA4 Structures --> Added new structures "EOLGainOffs1", "FilNotchRec1" and updated "MotPrmNomEolRec1".'...
                         '10) Common Functions --> Bug fix for "Val2String" script.'];
hist_DataMgt(15).date = '22-May-2015';

hist_DataMgt(16).ver =  '2.13.0';
hist_DataMgt(16).log =  ['1) Data Classes --> Client: Added check to ensure that .CallLocation property accepts only cell arrays of strings.'...
                         '2) Data Classes --> CSRetun: Updated string method to generate Return Parameter Name in Data Dictionary.'...
                         '3) Data Classes --> FDD: Removed .Dependencies property as new ImprtdCal data class has been released.'...
                         '4) Data Classes --> ImprtdCal: New Data class for handling Dependent Calibrations.'...
                         '5) Data Classes --> SrvRunnable: Enhanced the error handling mechanism for notifying users.'...
                         '6) CreateDD --> Added support for new Data class DataDict.ImprtdCal.'...
                         '7) CreateDD --> Added logic to automatically generate the correct "Data Dictionary name" based on the FDD information instead of "MyDataDict.m".'...
                         '8) CreateDD --> Improved error handling mechanism.'...
                         '9) VerifyDD --> Updated VerifyDD tool for accepting the EA program name as a input argument instead of user prompt.'...
                         '10) VerifyDD --> Added logic to notify User if Input or Output signals used in SrvRunnable data class are found only in DD alone but not in Model.'...
                         '11) VerifyDD --> Removed .Dependencies property check as new ImprtdCal data class has been released.'...
                         '12) VerifyDD --> Added support for new data class ImprtdCal.'...
                         '13) Common Functions --> Val2String:Updated logic to handle floating point numbers.'...
						 '14) EA4 Enumerations --> Added new enumeration "NvmGetErrSts1" for EA4 programs.'];
hist_DataMgt(16).date = '05-Jun-2015';

hist_DataMgt(17).ver =  '2.14.0';
hist_DataMgt(17).log =  ['1) Data Classes --> CSRetun: Removed .Name property from string method.'...
                         '2) Data Classes --> FDD: Retained .Dependencies property to support ImprtdCal data class.'...
                         '3) Data Classes --> FDD: Converted .Dependencies property as a default property of FDD data class for both EA3 & EA4 programs instead of EA4 programs alone.'...
						 '4) Data Classes --> FDD: Added logic to notify users if an old format is used for .Dependencies property.'...
                         '5) struct --> FilNotchStRec1: New Notch Filter data structure for EA4 programs.'...
                         '6) struct --> FilNotchGainRec1: New structure has been created for EA4 programs.'...
                         '7) struct --> HwAgOffs1: New structure has been created for EA4 programs.'...
                         '8) struct --> HwTqOffs1: New structure has been created for EA4 programs.'...
						 '9) struct --> MotPrmNomEolRec2: End of Line Motor Parameters structure has been updated for EA4 programs.'...
						 '10) VerifyDD --> Added logic to support multiple SrvRunnable variables usage in a single FDD.'...
						 '11) VerifyDD --> Added logic to handle Imported Calibrations in a better way.'...
						 '12) VerifyDD --> ModelDDTest: Added logic to parse only relevant portions of code based on Program type i.e. "EA3" or "EA4".'];
hist_DataMgt(17).date = '19-Jun-2015';

hist_DataMgt(18).ver =  '2.15.0';
hist_DataMgt(18).log =  ['1) Data Classes --> ImprtdCal: Updated String method such that EngMin is written first instead of EngMax.'...
                         '2) Data Classes --> ImprtdCal: Updated String method to populate .PortName in EA4 DD.'...
                         '3) Data Classes --> Calibration: Updated String method to populate .PortName in EA4 DD.'...
						 '4) Data Classes --> FDD: Removed ".Ntc" property from String method as new ".NTC" data class is introduced.'...
                         '5) Data Classes --> NTC: New Data class NTC has been developed.'...
						 '6) struct --> FilHpRec1: Suppressed code from generating output to command window.'...
						 '7) struct --> FltInjUsrPrmRec1: New Fault Injection canape structure for EA4 programs.'...
						 '8) struct --> NtcFltInfoRec2: Updated structure of NTCs stored in RAM.'...
						 '9) struct --> NtcInfoRec2: Updated High-pass filter structure for EA4 programs.'...
						 '10) struct --> NtcMapRec1: New structure for EA4 programs.'...
						 '11) struct --> EOLGainOffsRec1: New End-of-Line Current Measurement parameters structure for EA4 programs.'...
						 '12) struct --> HwAgOffsRec1: New Handwheel Angle Offset NvM structure for EA4 programs.'...
						 '13) struct --> HwTqOffsRec1: New Handwheel Torque Offset NvM structure for EA4 programs.'...
						 '14) CommonFunctions --> Val2String: Modified the "case {"struct","structEA3"}" section with addition of error handling, three more data types, and 1 bug fix.'];
hist_DataMgt(18).date = '10-July-2015';

hist_DataMgt(19).ver =  '2.16.0';
hist_DataMgt(19).log =  ['1) Data Classes --> ImprtdCal: Supressed code writing of duplicate .PortName in EA4 DD.'...
                         '2) Data Classes --> ImprtdCal: "UNDEFINED" declared for initial .PortName value in EA4 DD.'...
                         '3) Data Classes --> Calibration: Supressed code writing of duplicate .PortName in EA4 DD.'...
                         '4) Data Classes --> Calibration: "UNDEFINED" declared for initial .PortName value in EA4 DD.'];
hist_DataMgt(19).date = '17-July-2015';

hist_DataMgt(20).ver =  '2.17.0';
hist_DataMgt(20).log =  ['1) Data Classes --> Calibration: Replaced "Controls" choice with three new choices for .TuningOwner property.'...
                         '2) Data Classes --> NVM: Removed check to make sure arrays of structures were not defined.'...
						 '3) Data Classes --> PIM: Removed check to make sure arrays of structures were not defined.'...
                         '4) EA4 Enumerations --> MfgEnaSt1: New Manufacturing Enable State enumeration has been created.'...
						 '5) EA4 Enumerations --> NtcNr2: New NTC number enumeration has been created.'...
                         '6) struct --> FilHpRec1: Fixed InitString to create appropriate structure.'...
                         '7) struct --> FltInjUsrPrmRec1: Added LoglFlt before anyone else has used this struct. Not incrementing file name.'...
						 '8) struct --> FltInjUsrPrmRec1: Reordered elements by datatype, biggest-to-smallest.  Not incrementing file name.'...
						 '9) struct --> FltInjUsrPrmRec1: FltInjLoc now FltLocn per Autosar.  HwVelThd units & range changed.  Not incrementing file name.'...
						 '10) struct --> NtcFltInfoRec2: Bug fix for engineering datatype of NtcNr. Was a u16, it needs to be an NtcNr enumerated value.'...
						 '11) struct --> NtcInfoRec3: Updated Diagnostic manager structure for EA4 programs.'...
						 '12) CommonFunctions --> Val2String: Fixed bug for structure of structures causing errors in both the val2string_no_dt and val2string_with_dt functions.'...
						 '13) CommonFunctions --> Val2String: Added logic to the val2string_with_dt to handle structures with enumerated values.'];
hist_DataMgt(20).date = '05-Aug-2015';

hist_DataMgt(21).ver =  '2.18.0';
hist_DataMgt(21).log =  ['1) Data Classes --> NTC: Changed the class that DataDict.NTC inherits from to AUTOSAR.Parameter.'...
                         '2) Data Classes --> NTC: Added logic to allow ConfigParams to be the NtcNr.'...
						 '3) Data type --> sm5p12: New Data type created for EPS programs.'...
						 '4) struct --> MotPrmNomEolRec3: End of Line Motor Parameters structure used for EA4.'];
hist_DataMgt(21).date = '20-Aug-2015';

hist_DataMgt(22).ver =  '2.19.0';
hist_DataMgt(22).log =  ['1) struct --> CurrMeasEolGainCalRec1: End-of-Line Current Measurement paramters structure used for EA4 programs.'...
                         '2) struct --> CurrMeasEolOffsCalRec1: End-of-Line Current Measurement paramters structure used for EA4 programs.'...
						 '3) struct --> MotAgMeasEolPrmRec1: Added datatype casting in the CreateObj() function to avoid any Min/Max errors with the Simulink Bus.'];
hist_DataMgt(22).date = '01-Sept-2015';

hist_DataMgt(23).ver =  '2.20.0';
hist_DataMgt(23).log =  ['1) EA4 Enumerations --> TrigReg1: New Trigger Register Enumeration for EA4 programs.'...
                         '2) EA4 Enumerations --> SysSt1: The default value for this enum was SYSST_DI which was not the default for the system this was corrected.'...
						 '3) struct --> CodFlsAdrRec1: New Code Flash Address parameters structure for EA4 programs.'...
						 '4) struct --> CurrMeasEolGainCalRec1: Bug fix for End-of-line current measurement parameter structure.'];
hist_DataMgt(23).date = '15-Sept-2015';

hist_DataMgt(24).ver =  '2.21.0';
hist_DataMgt(24).log =  '1) struct --> EotNvmDataRec1: New End of Travel Parameters structure used for EA4 programs.';
hist_DataMgt(24).date = '24-Sept-2015';

hist_DataMgt(25).ver =  '2.22.0';
hist_DataMgt(25).log =  ['1) Data Types --> struct: Support for arrays of structures was added.'...
                         '2) Data Classes --> Calibration: Changed GraphLink to be a cell array and created the logic to convert the old style to the new style.'...
						 '3) Data Classes --> Calibration: Made default value for MaxGrad to Inf.'...
						 '4) Data Classes --> Calibration: Set the ProgrammedBy property to be hidden.'...
						 '5) Data Classes --> Calibration: For the TuningOwner property logic was added to prevent "Controls" from being set as the assigned value.'...
						 '6) Data Classes --> ConfigParam: New property IsBuildPrm was added along with logic to ensure that the property is either true or false.'...
						 '7) Data Classes --> NVM: The behavior of the EngInit and InitRowCol properties was changed to support explicit arrays of structures and to prevent warnings when EngInit is [] and InitRowCol is not [1 1].'...
						 '8) Data Classes --> Runnable: Added Context property and logic to enforce accepted values.'...
						 '9) EA4 Enumerations --> McuDiagc1: New Microcontroller Diagnostics Enumeration for EA4 programs.'...
						 '10) struct --> CodFlsAdrRec1: Bug fix in calculation of structure Minimums and Maximums.'...
						 '11) struct --> DutyCycThermProtnFilStValRec1: New Duty Cycle Thermal Protection Filter State Value structure for EA4 programs'...
						 '12) CommonFunctions --> Val2String: Support for arrays of structures was added.'];
hist_DataMgt(25).date = '09-Oct-2015';

hist_DataMgt(26).ver =  '2.23.0';
hist_DataMgt(26).log =  ['1) Data Classes --> Calibration: Bug Fix: Inconsistency between allowed values for Cardinality and values being check by the set method for the Cardinality property.'...
                         '2) struct --> MotPrmNomEolRec3: Fixed bug in function CreateBusObj to ensure that correct value is written to the min and max of the Simulink bus.'...
						 '3) Val2String --> Fixed bug for structures with enums where the initial value is [].'];
hist_DataMgt(26).date = '15-Oct-2015';

hist_DataMgt(27).ver =  '2.24.0';
hist_DataMgt(27).log =  ['1) Data Types --> struct: Support for variable EngMin and EngMax has been added.'...
                         '2) Data Classes --> Calibration: Changed default value for ProgrammedBy property from "?" to "Nexteer".'...
                         '3) Data Classes --> Calibration: Fixed list of AllowedValues for Cardinality and warning message from Init to Inin.'...
                         '4) Data Classes --> Calibration: Fixed warning message for TuningOwner selection to say Calibration.TuningOwner instead of NVM.TuningOwner.'...
                         '5) Data Classes --> NVM: The ProgrammedBy property was hidden and removed from the string method.'...
                         '6) Data Classes --> NVM: Added "ThermMngt", "PwrMngt" and "TqCtrl" to the list of options for TuningOwner.'...
                         '7) Data Classes --> NVM: The SafetyRating property was hidden.'...
                         '8) Data Classes --> Runnable: Enabled and Initialized .Context property to "Rte".'];
hist_DataMgt(27).date = '21-Oct-2015';

hist_DataMgt(28).ver =  '2.25.0';
hist_DataMgt(28).log =  '1) Data Classes --> NVM: Fixed bug in String method, when writing the EngMin and EngMax.';
hist_DataMgt(28).date = '26-Oct-2015';

hist_DataMgt(29).ver =  '2.26.0';
hist_DataMgt(29).log =  ['1) Data Classes --> PIM: Updated String method for populating EngMin and EngMax correctly.'...
                         '2) EA4 Enumerations --> HwAgTrajCmdSt1: Handwheel Angle Trajectory Command State enumeration for EA4 programs.'...
						 '3) EA4 Enumerations --> HwTqVldSnsr1: Handwheel Torque Valid Sensor enumeration for EA4 programs.'];
hist_DataMgt(29).date = '04-Nov-2015';

hist_DataMgt(30).ver =  '2.27.0';
hist_DataMgt(30).log =  ['1) Base Types: structelement: New property "Dimensions" has been added.'...
                         '2) struct --> DiagcData1: New structure for passing parameters to SetNtcSts and DiagcMgrPer2 function in various EA4 programs.'...
						 '3) struct --> NtcInfoRec4: Updated Diagnostic manager for EA4 programs.'...
						 '4) struct --> ReadFltInfoRec1: New structure of NTCs used to Read NTCs using the CMS function from the ReadNtcFltAry Server in various EA4 programs.'...
						 '5) structEA3 --> SnsrLrndOffs_Str: New Sensor Learned Offset structure for EA3 programs.'...
						 '6) CommonFunctions --> Val2String: Added better error handling for input values with incorrect datatypes.'...
						 '7) EA3 Enumerations --> FltInjectionLocType: Updated FAULT INJECTION LOCATION enumerations.'];
hist_DataMgt(30).date = '21-Dec-2015';

hist_DataMgt(31).ver =  '2.28.0';
hist_DataMgt(31).log =  '1) CommonFunctions --> Val2String: The wrong file was used for the desired changes the correct baselined file was used and the new error checking content was added.';
hist_DataMgt(31).date = '23-Dec-2015';

hist_DataMgt(32).ver =  '2.29.0';
hist_DataMgt(32).log =  ['1) Data Classes: Calibration: Added Logl as a posibility for Element Name in the CoderInfo property.'...
                         '2) Data Classes: PIM: Fixed bug in code to write InitialValue property when the EngDT is an enumeration.'...
						 '3) EA4 Enumerations --> CrcHwResvCfg1: New CRC Hardware reserve configuration enumeration for EA4 programs.'...
						 '4) EA4 Enumerations --> CrcHwResvMod1: New CRC Hardware reserve mode enumeration for EA4 programs.'...
						 '5) EA4 Enumerations --> CrcHwSts1: New CRC Hardware status enumeration for EA4 programs.'...
						 '6) EA4 Enumerations --> All Enumerations: Changed class so that the class name was not appended to the beginning of the enum when it is coded.'...
						 '7) struct --> CrcHwStsRec1: New Synchronous CRC structure for EA4 programs.'];
hist_DataMgt(32).date = '14-Jan-2016';

hist_DataMgt(33).ver =  '2.30.0';
hist_DataMgt(33).log =  ['1) Data Classes: CSArguments: Fixed bug in String function where structures were not written correctly.'...
                         '2) Data Classes: NVM: Fixed bug that writes "[ 0]" when the EngInit value is set to [].'...
						 '3) EA4 Enumerations --> McuDiagc2: New Microcontroller Diagnostics enumeration for EA4 programs.'...
						 '4) struct --> DiagcDataRec1: New structure to pass parameters to SetNtcSts in EA4 programs.'...
                         '5) struct --> MotRplCoggPrmRec1: New Motor Ripple Cogging Parameters structure for EA4 programs.'...
                         '6) struct --> SnsrLrndOffsRec1: New structure for EA4 programs.'...
                         '7) struct --> NtcInfoRec4: Removed "DebCntr" structure element.'];
hist_DataMgt(33).date = '01-Feb-2016';

hist_DataMgt(34).ver =  '2.31.0';
hist_DataMgt(34).log =  ['1) struct --> AnHwTqScaFacRec1: New Analog Handwheel Torque Sensor Scale Sactor structure for EA4 programs.'...
                         '2) struct --> SnsrLrndOffsRec1: New structure used for EA4 programs.'...
						 '3) EA4 Enumerations --> GmSysPwrMod1: New GM System Power Mode enumeration for EA4 programs.'...
                         '4) CommonFunctions --> Val2String: Fixed bugs in internal function val2string_with_dt.'];
hist_DataMgt(34).date = '05-Feb-2016';

hist_DataMgt(35).ver =  '2.32.0';
hist_DataMgt(35).log =  ['1) struct --> CurrMeasEolOffsGainCalRec1: New End-of-Line Current Measurement Offset and Gain Parameters structure used for EA4 Single Inverter programs.'...
                         '2) struct --> PassFailCntrDiagcRec1: New low-pass filter structure for EA4 programs.'...
						 '3) EA4 Enumerations --> StHlthMonSig1: New State Health Monitor Signal enumeration for EA4 programs.'];
hist_DataMgt(35).date = '11-Feb-2016';

hist_DataMgt(36).ver =  '2.33.0';
hist_DataMgt(36).log =  ['1) struct --> MotRplCoggPrmRec1: Bug fixed in the function that creates the Simulink.Bus in the workspace.'...
                         '2) struct --> PassFailCntrDiagcRec1: Reorder of structure elements to comply with standards.'];
hist_DataMgt(36).date = '25-Feb-2016';

hist_DataMgt(37).ver =  '2.34.0';
hist_DataMgt(37).log =  ['1) struct --> CurrMeasEolOffsGainCalRec1: Fixed bug in obj.InitString.'...
                         '2) struct --> PassFailCntrDiagcRec1: Fixed order of elements to follow standards.'];
hist_DataMgt(37).date = '02-Mar-2016';

hist_DataMgt(38).ver =  '2.35.0';
hist_DataMgt(38).log =  ['1) struct --> NtcMapRec2: High-pass Filter structure used in EA4 programs.'...
                         '2) struct --> SysFricDataRec1: Sensor Learned Offset NVM structure used for EA4 programs.'...
						 '3) struct --> SysFricDataRec2: High pass filter structure used for EA4 programs.'...
						 '4) EA3 Enumerations --> APA_State: APA state enumeration for EA3 programs.'...
						 '5) EA3 Enumerations --> ESC_State: ESC state enumeration for EA3 programs.'...
						 '6) EA3 Enumerations --> Haptic_State: Haptic state enumeration for EA3 programs.'...
						 '7) EA3 Enumerations --> LKA_state: LKA state enumeration for EA3 programs.'...
						 '8) EA3 Enumerations --> sesState: ses state enumeration for EA3 programs.'...
						 '9) EA4 Enumerations --> DtcIdxQlfrSts1: Diagnostic trouble code index qualifier status enumeration for EA4 programs.'...
						 '10) EA4 Enumerations --> SysFricLrngOperMod1: Friction Learning Mode Signal enumeration for EA4 programs.'];
hist_DataMgt(38).date = '15-Mar-2016';

hist_DataMgt(39).ver =  '2.36.0';
hist_DataMgt(39).log =  ['1) Data Classes: Client: Added Description property.'...
                         '2) Data Classes: CSArguments: In the String method EngDT was put before EngMin and Eng. Description property was added. '...
                         '3) Data Classes: CSReturn: Added Description property.'...
                         '4) Data Classes: IpSignal: Added Description property.'...
                         '5) Data Classes: Runnable: Added Description property.'...
                         '6) Data Classes: SrvRunnable: Added Description property.'...
                         '7) Data Classes: ImprtdCal: Added Description property.'...
                         '8) EA4 Enumeration: Added EgyModSt1: Energy mode state is a signal used by the system to indicated acceptable levels of energy usage.'...
                         '9) EA4 Structure: Added SysFricNonLrngDataRec1'];
hist_DataMgt(39).date = '22-Mar-2016';

hist_DataMgt(40).ver =  '2.37.0';
hist_DataMgt(40).log =  ['1) Data Classes: IpSignal: Removed duplication of Description property.'...
                         '2) EA4 Enumerations --> McuDiagc1: Merged McuDiagc2 with McuDiagc1.'...
                         '3) EA4 Enumerations --> McuDiagc2: Removed permanently and transferred all its contents to McuDiagc1.'...
                         '4) EA3 Enumerations --> NTCNum: Added new NTC number "NTC_Num_LimpHomeIgnitionCounter".'...'
                         '5) strct --> HwAgSnsrTrimRec1: New Handwheel Angle Sensor Trim NVM structure for EA4 programs.'...
                         '6) strctEA3 --> EOTLearned_Str: New Learned End of Travel Data NVM strcture for EA3 programs.'];
hist_DataMgt(40).date = '22-Mar-2016';

hist_DataMgt(41).ver =  '2.38.0';
hist_DataMgt(41).log =  ['1) Data Classes: CSArguments: Added to logic to supress the unnecessary warnings that are getting generated while parsing Data Dictionary files using VerifyDD tool.'...
                         '2) Data Classes: Constant: Removed .Header property from Constant data class.'...
						 '3) Data Classes: FDD: Removed .Dependencies property.'...
						 '4) Data Classes: Runnable: Replaced "Non-Rte" with "NonRte" keyword for .Context property.'...
						 '5) Data Classes: SrvRunnable: Replaced "Non-Rte" with "NonRte" keyword for .Context property.'...
						 '6) EA3 Enumerations --> "Rte_Type.h" file reference has been removed from all enumeration files.'...
						 '7) EA4 Enumerations --> DtcIdxQlfrSts1: Removed permanently from tools package.'...
                         '8) EA4 Enumerations --> DtcIdxSts1: New Diagnostic Trouble Code Index Status enumeration for EA4 programs.'...
                         '9) EA4 Enumerations --> StHlthTaskRef1: Added new State Health Task reference enumeration for EA4 programs.'...
						 '10) EA4 Enumerations --> EgyModSt1: Bug fix for Energy mode state enumeration.'...
						 '11) EA4 Enumerations --> McuDiagc1: Added new constants.'...
						 '12) EA4 Enumerations --> Dem_DTCFormatType: New DTC Type Enumeration for EA4 programs.'...
						 '13) EA4 Enumerations --> Dem_DTCOriginType: New DTC Origin Type enumeration for EA4 programs.'...
						 '14) EA4 Enumerations --> Dem_EventStatusType: New Event Status Type enumeration for EA4 programs.'...
						 '15) EA4 Enumerations --> Dem_ReturnClearDTCType: New DEM Return Clear DTC Type enumer for EA4 programs.'...
                         '16) EA4 Enumerations --> "Rte_Type.h" file reference has been removed from all enumeration files.'...
						 '17) strct --> StHlthSigStcPrmRec1: New Configuration structure for EA4 programs.'...
						 '18) CommonFunctions --> Val2String: Fixed bug in val2string_with_dt for when the value being converted is an enumeration in a structure.'];
hist_DataMgt(41).date = '15-Apr-2016';


hist_DataMgt(42).ver =  '2.39.0';
hist_DataMgt(42).log =  ['1) Data Classes: ConfigParam: Removed .Header property from ConfigParam data class.'...
                         '2) Data Classes: CSRetun: Added logic to remove .Description property when Return Type is "None".'...						 
						 '3) EA4 Enumerations --> DtcIdxSts1: Removed permanently from tools package as none of the FDDs are using this enumeration.'...
                         '4) EA4 Enumerations --> NtcNrWithResd1: New NTC Number with Reserved bit enumeration for EA4 programs.'...
                         '5) EA4 Enumerations --> StHlthMonSig2: Added new State Health Monitor Signal Status enumeration for EA4 programs.'...
						 '6) strct --> MotRplCoggPrmRec2: Added new Motor Ripple Cogging Parameters structure for EA4 programs.'...
						 '7) struct --> ReadFltInfoRec1: Datatype has been updated to "NtcNrWithResd1". But structure has not been incremented as design and implementation are using the same version.'];
hist_DataMgt(42).date = '29-Apr-2016';


hist_DataMgt(43).ver =  '2.40.0';
hist_DataMgt(43).log =  ['1) Data Classes: ​Runnable: ​Added logic to automatically convert "Non-Rte" to "NonRte" keyword for .Context property.'...
                         '2) EA4 Enumerations --> ​EgyModSt1: ​Updated the Base Datatype.'...
                         '3) struct --> MaxHwAgCwAndCcwRec1: Added new ​Maximum Clockwise and Counter Clockwise H​andwheel Angle Parameters Structure for EA4 programs.'];
hist_DataMgt(43).date = '17-May-2016';


hist_DataMgt(44).ver =  '2.41.0';
hist_DataMgt(44).log =  ['1) Data Classes: CSArguments: Added .TestTolerance property.'...
                         '2) EA3 Enumerations --> SS_State: New Stop Mode enumeration for EA3 Programs.'...
                         '3) EA3 Enumerations --> PwrDiscnctSt1: New Power Disconnect State Enumeration for EA3 Programs.'];
hist_DataMgt(44).date = '02-Jun-2016';

hist_DataMgt(45).ver =  '2.42.0';
hist_DataMgt(45).log =  ['1) EA3 Enumerations --> ImcSigSts: New Inter-Micro Communication Arbiter Enumeration for EA3 programs.'...
                         '2) EA3 Enumerations --> SteerMod: New Steering Mode Enumeration for EA3 programs.'...
                         '3) structEA3 --> SysOutpCpbySig_Str: New System Output Capability Signal structure for EA3 programs.'...
                         '4) struct --> SnpshtDataRec1: New Snapshot Data Record structure for EA4 programs.'...
                         '5) struct --> StordLstPrmRec1: New Stored Last Parameters structure for EA4 programs.'...
                         '6) struct --> NtcFltInfoRec1?: ?Updated the datatype and range of "NtcNr" strcuture element.? Revision number has not been incremented as it is being used in software.?'...
						 '7) EA4 Enumerations --> GmFctDiArbnSts1: New GM Function Disable Arbitration Enumeration for EA4 programs.'];
hist_DataMgt(45).date = '22-Jun-2016';


hist_DataMgt(46).ver =  '2.43.0';
hist_DataMgt(46).log =  '1) EA3 Enumerations --> FcaTqOvrlSt: New FCA Torque Overlay State Enumeration for EA3 programs.';
hist_DataMgt(46).date = '23-Jun-2016';

hist_DataMgt(47).ver =  '2.44.0';
hist_DataMgt(47).log =  ['1) EA3 Enumerations --> BattVltgSt_Cnt_enum: New Battery Voltage State Enumeration for EA3 programs.'...
                         '2) EA3 Enumerations --> SysPrfmncSt_Cnt_enum: New Ststem Performance State Enumeration for EA3 programs.'];
hist_DataMgt(47).date = '07-Jul-2016';

hist_DataMgt(48).ver =  '2.45.0';
hist_DataMgt(48).log =  ['1) EA3 Enumerations --> BattVltgSt: Renamed enumeration from "BattVltgSt_Cnt_enum" to "BattVltgSt" for EA3 programs.'...
                         '2) EA3 Enumerations --> SysPrfmncSt: Renamed enumeration from "SysPrfmncSt_Cnt_enum" to "SysPrfmncSt" for EA3 programs.'...
						 '3) EA3 Enumerations --> GmPosnOvrlSt: New GM Position Overlay State Enumeration for EA3 programs.'...
						 '4) EA3 Enumerations --> GmHwAgCmdLimSt: New GM Handwheel Angle Command Limit State Enumeration for EA3 programs.'...
						 '5) CommonFunctions  --> MinMax2String: Added functionaity to support structures.'];
hist_DataMgt(48).date = '15-Jul-2016';

hist_DataMgt(49).ver =  '2.46.0';
hist_DataMgt(49).log =  ['1) Data Classes --> IpSignal: Bug fix for .ReadIn property.'...
                         '2) Data Classes --> OpSignal: Bug fix for .WrittenIn property.'...
						 '3) Data Classes --> IRV: Bug fix for .ReadIn & .WrittenIn properties.'...
						 '4) EA3 Enumerations --> GmHwAgAuthReqSt: New GM Handwheel Angle Authorization Request State enumeration for EA3 programs.'...
						 '5) EA3 Enumerations --> FcaTqOvrlSt: Prefixed all element names with customer name.'...
						 '6) EA3 Enumerations --> GmHwAgCmdLimSt: Prefixed all element names with customer name.'...
						 '7) EA3 Enumerations --> GmPosnOvrlSt: Prefixed all element names with customer name.'...
						 '8) struct --> PassFailCntrDiagcRec1: Updated Initialization String to match the structure elements order.'];
hist_DataMgt(49).date = '12-Sep-2016';

hist_DataMgt(50).ver =  '2.47.0';
hist_DataMgt(50).log =  ['1) Data Classes --> FDD: Added support for Development Data Dictionary.'...
                         '2) Data Classes --> Sig: New Signal Data class added for supporting Development functions.'...
						 '3) Data Classes --> Prm: New Parameter Data class added for supporting Development functions.'];
hist_DataMgt(50).date = '19-Sep-2016';

hist_DataMgt(51).ver =  '2.48.0';
hist_DataMgt(51).log =  '1) EA4 Enumerations --> StHlthMonSig3: New State of Health Monitor Signal enumeration for EA4 programs.';
hist_DataMgt(51).date = '22-Sep-2016';

hist_DataMgt(52).ver =  '2.49.0';
hist_DataMgt(52).log =  ['1) EA3 Enumerations --> NTCNum: Added New NTC Number "NTC_Num_EcuCrossChk" to support ECU Cross check function.'...
                         '2) struct --> DiagcDataRec1: Suppressed command window prompts during structre creation.'];
hist_DataMgt(52).date = '19-Oct-2016';

hist_DataMgt(53).ver =  '2.50.0';
hist_DataMgt(53).log =  ['1) EA3 Enumerations --> CaApaAbortSt: New ChangAn APA Abort State enumeration for EA3 programs.'...
                         '2) EA3 Enumerations --> CaApaReqSt: New ChangAn APA Request State enumeration for EA3 programs.'...
                         '3) EA3 Enumerations --> CaLdwSt: New ChangAn LDW State enumeration for EA3 programs.'...
                         '4) EA3 Enumerations --> CaLkaSt: New ChangAn LKA State enumeration for EA3 programs.'...
                         '5) EA3 Enumerations --> NTCNum: New NTC number "NTC_Num_IMCHiOffsCorrn (151)" for EA3 programs.'...
                         '6) structEA3 --> SnsrLrndOffs_Str: Updated dimensions of "YawRateOffs","HwTqOffs","HwAgLrngYawOffsRef" & "HwAgLrngSysTqFilSt" elements.'...
                         '7) EA4 Enumerations --> BattVltgSt1: New Battery Voltage State enumeration for EA4 programs.'...
                         '8) EA4 Enumerations --> ImcArbnRxDataSrc1: New IMC Arbitration Receive Data Source enumeration for EA4 programs.'...
                         '9) EA4 Enumerations --> ImcArbnRxSts1: New IMC Arbitration Receive Status enumeration for EA4 programs.'...
                         '10) EA4 Enumerations --> ImcSigSts1: New IMC Signal Status enumeration for EA4 programs.'...
                         '11) EA4 Enumerations --> PwrDiscnctSt1: New Power Disconnection Status enumeration for EA4 programs.'...
                         '12) EA4 Enumerations --> SteerMod1: New Steer Mode enumeration for EA4 programs.'...
                         '13) struct --> SnsrLrndOffsRec2: New Sensor Learned Offset structure for EA4 programs.'...
                         '14) struct --> StHlthSigStcPrmRec2: New State of Health Signal Statastic configuration structure for EA4 programs.'...
                         '15) struct --> SysOutpCpbySigRec1: New System Output Capability structure for EA4 programs.'...
                         '16) struct --> EotNvmDataRec2: New structure added for End Of Travel Parameters structure.'];
hist_DataMgt(53).date = '15-Nov-2016';


hist_DataMgt(54).ver =  '2.51.0';
hist_DataMgt(54).log =  ['1) EA4 Enumerations --> ImcSigSts1: Removed permanently from tools package.'...
                         '2) struct --> MaxHwAgCwAndCcwRec2: New structure added for End Of Travel Parameters structure.'...
                         '3) struct --> EotNvmDataRec2: Removed permanently from tools package.'];
hist_DataMgt(54).date = '20-Nov-2016';

hist_DataMgt(55).ver =  '2.52.0';
hist_DataMgt(55).log =  ['1) EA4 Enumerations --> GmHwAgAuthnReqSt1: New GM Handwheel Angle Authorization Request State enumeration for EA4 programs.'...
                         '2) EA4 Enumerations --> GmHwAgCmdLimSt1: New GM Handwheel Angle COmmand Limited State enumeration for EA4 programs.'...
                         '3) EA4 Enumerations --> GmPosnOvrlSt1: New GM Position Overlay State enumeration for EA4 programs.'...
						 '4) EA4 Enumerations --> GmTqArbnEscSt1: New GM Torque Arbitration ESC State enumeration for EA4 programs'...
						 '5) EA4 Enumerations --> GmTqArbnLkaSt1: New GM Torque Arbitration LKA_state enumeration for EA4 programs.'...
						 '6) EA3 Enumerations --> PwPckTqDStatType: New enumeration for EA3 programs.'...
						 '7) EA3 Enumerations --> NTCNum: New NTC number "NTC_Num_PHAPosnSnsrVsPwrpkDataWrong" was added for EA3 programs.'...
						 '8) EA3 Enumerations --> NTCNum: New NTC number "NTC_Num_PHAScratchPadTrf" was added for EA3 programs.'...
						 '9) struct --> WhlImbRejctnCmpPeakRec1: New Wheel Imbalance Rejection Compensation Peak Record structure for EA4 programs.'...
						 '10) EA4 Enumerations --> ImcArbnRxExtdSts1: New IMC Arbitration Receive Extended Status enumeratiuon for EA4 programs.'...
						 '11) EA4 Enumerations --> ImcArbnRxDataSrc1: Replaced all the element names with new element names.'...
						 '12) EA4 Enumerations --> ImcArbnRxSts1: Corrected element names as per standards.'];			 
hist_DataMgt(55).date = '13-Jan-2017';

hist_DataMgt(56).ver =  '2.53.0';
hist_DataMgt(56).log =  ['1) EA4 Enumerations --> GmOvrlStMgrApaSt1: New GM Overlay State Manager APA State enumeration for EA4 programs.'...
                         '2) EA4 Enumerations --> GmOvrlStMgrHaptcSt1: New GM Overlay State Manager Haptic State enumeration for EA4 programs.'...
                         '3) EA3 Enumerations --> TuningSessionAddrPtrEnum: New Tuning Session Address Pointer enumeration for EA3 programs.'...
						 '4) EA3 Enumerations --> NTCNum: New NTC number "NTC_Num_PHAPosnSnsrVsPwrpkDataWrong" was added for EA3 programs.'...
                         '5) EA4 Enumerations --> SelnCaseSt1: New Selection Case State enumeration for EA4 programs.'...
                         '6) structEA3 --> PsaAgArbnLrndOffs_Str: New PSA Angle Arbitration Learned Offset structure for EA3 programs.'];			 
hist_DataMgt(56).date = '30-Jan-2017';

hist_DataMgt(57).ver =  '2.54.0';
hist_DataMgt(57).log =  ['1) EA4 Enumerations --> GmSysPwrMod1: Added new element "GMSYSPWRMOD_PRPN" for gloabl B programs.'...
                         '2) EA3 Enumerations --> PsaAgArbnDiagCmdReq: New PSA Angle Arbitration Diagnostics Command Request enumeration for EA3 programs.'...
                         '3) EA3 Enumerations --> PsaAgArbnSnsrMod: New PSA Angle Arbitration Sensor Mode enumeration for EA3 programs.'...
						 '4) EA3 Enumerations --> PsaAgArbnSt: New PSA Angle Arbitration State enumeration for EA3 programs.'...
						 '5) struct --> CurrMeasEolOffsCalRec1: Updated EngMax value of "CurrMeasEolOffsHiBrdgVltg" from 1325008 to 1892865.'];
hist_DataMgt(57).date = '02-Mar-2017';

hist_DataMgt(58).ver =  '2.55.0';
hist_DataMgt(58).log =  ['1) EA4 Enumerations --> GmAutnmsDrvgIfFltRespDi1: New GM Autonomous Driving Fault Response Disable enumeration for EA4 programs..'...
                         '2) EA4 Enumerations --> GmAutnmsSteerCmdSts1: New GM Autonomous Steering Command Status enumeration for EA4 programs.'...
                         '3) EA4 Enumerations --> GmDrvrIntvDetnSt1: New GM Driver Intervention Detection Status enumeration for EA4 programs.'...
						 '4) EA4 Enumerations --> GmDualEcuOperSts1: New GM Dual ECU Operation Status enumeration for EA4 programs.'...
                         '5) EA4 Enumerations --> GmSteerCmdLimrSt1: New GM Steering Command Limiter Status enumeration for EA4 programs.'...
                         '6) EA4 Enumerations --> GmSteerCmdMsgSrc1: New GM Steering Command Message Source enumeration for EA4 programs.'...
                         '7) EA4 Enumerations --> GmSteerCmdMsgSts1: New GM Steering Command Message Status enumeration for EA4 programs.'...
                         '8) EA4 Enumerations --> GmVehHlthMgrSt1: New GM Vehicle Health Manager Status enumeration for EA4 programs.'...
                         '9) EA4 Enumerations --> GmVehModMgrSt1: New GM Vehicle Mode Manager Status enumeration for EA4 programs.'...
                         '10) EA4 Enumerations --> Spi_SeqResultType: New SPI Sequence enumeration for EA4 programs.'...
                         '11) EA4 Enumerations --> GmSteerMod1: New GM Steer Mode enumeration for EA4 programs.'...
						 '12) DataDict --> CSReturn: Added support to include AUTOSAR specified return types.'...
						 '13) struct --> CurrMeasEolGainCal3PhaRec1: New End-of-Line Current Measurement Gain paramters structure used for EA4 programs.'...
						 '14) struct --> CurrMeasEolOffsCal3PhaRec1: New End-of-Line Current Measurement Offset paramters structure used for EA4 programs.'];
hist_DataMgt(58).date = '03-Apr-2017';

hist_DataMgt(59).ver =  '2.56.0';
hist_DataMgt(59).log =  ['1) EA4 Enumerations --> NtcNr2: Removed form tools package and all references to NtcNr2 should be replaced with NtcNr1.'...
                         '2) EA4 Enumerations --> GmAutnmsSteerCmdSts1: Corrected keyword abbreviation for Active.'...
                         '3) EA4 Enumerations --> GmDrvrIntvDetnSt1: Removed extra characters in element names.'...
                         '4) EA3 Enumerations --> FltInjectionLocType: Added new Fault Injection Constant FLTINJ_BMWTOC for CF040A component.'...
                         '5) EA3 Enumerations --> HaitecApaAbortSt: New Haitec APA Abort State enumeration for EA3 programs.'...
                         '6) DataDict --> NTC: Replaced reference to NtcNr2 with NtcNr1 enumeration.'...
                         '7) struct --> NtcFltInfoRec2: Replaced NtcNr2 with NtcNrWithResd1 enumeration.'...
                         '8) struct --> DiagcDataRec2: Updated data type of DiagcSts from b16 to b08.'...
                         '9) struct --> SnpshtDataRec2: Moved up IgnCntr to position 2 for NvM data optimization, Added SpclSnpshtData0, SpclSnpshtData1 and SpclSnpshtData2 & Removed VehSpd.'];
hist_DataMgt(59).date = '27-Apr-2017';

hist_DataMgt(60).ver =  '2.57.0';
hist_DataMgt(60).log =  ['1) EA3 Enumerations --> GmStrtStopSt: New GM Start Stop State enumeration for EA3 programs.'...
                         '2) EA3 Enumerations --> PsaTunModSt: New PSA Tuning Mode State enumeration for EA3 programs.'...
                         '3) EA3 Enumerations --> PwrDiscnctCfgASt1: New Power Discnnect State configuration A Enumeration for EA3 programs.'...
                         '4) EA3 Enumerations --> PwrDiscnctSt2: New Power Discnnect State Enumeration for EA3 programs.'...
                         '5) EA4 Enumerations --> McuDiagc1: Added new constant MCUDIAGC_CODFLASHEXECENAREGFAIL for EA4 programs.'...
                         '6) struct --> DutyCycExcddData1: New DutyCycle Exceeded Data structure for EA4 programs'];
hist_DataMgt(60).date = '25-May-2017';

hist_DataMgt(61).ver =  '2.58.0';
hist_DataMgt(61).log =  ['1) struct --> DutyCycExcddDataRec1: Renamed as per the naming conventions and deleted "DutyCycExcddData" structure from tools.'...
                         '2) struct --> MotAgEolPrmRec1: New Motor Angle End Of Line parameters structure for EA4 programs.'...
                         '3) struct --> MotAgRtPrmRec1: New Motor Angle Runtime Parameter structure for EA4 programs.'...
                         '4) struct --> MotAgStVariRec1: New Motor Angle State Variable Structure for EA4 programs.'...
                         '5) EA4 Enumerations --> StHlthMonSig4: New State of Health Monitoring Sginal enumeration for EA4 programs.'];
hist_DataMgt(61).date = '05-Jun-2017';

hist_DataMgt(62).ver =  '3.0.0';
hist_DataMgt(62).log =  ['1) Data Classes --> Runnables: Enabled Runnable concept for EA3 programs.'...
                         '2) Data Classes --> SrvRunnable: Enabled  Server Runnable concept for EA3 programs.'];
hist_DataMgt(62).date = '16-Jun-2017';

