%  NxtrKeyWrdRpt tool is mainly useful for finding a Signal or Paramter name
%  in the Unknown Keyword list and reports the same back to our Data
%  Dictionary creation tool.
%  If a Signal or Parameter is part of Unknown Keyword list then an error
%  message along with an updated Error count would be returned by this tool.
%           UnKnKeyWrd_lst -- Unknown Keyword List generated by NxtrKeyWrdMgr tool.
%           SPName         -- Signal or Paramter name
%           str            -- Current string information used by CreateDD tool.
%           nEr            -- Current error count information used by CreateDD tool.
%
