%  NxtrKeyWrdMgr tool is mainly useful for identifying Unknown Keywords
%  usage inside a Signal or Paramter name.
%  If a Signal or Parameter is using a Unknown Keyword then NxtrKeyWrdMgr
%  would populate all those keywords and returns a list of such Keywords.
%           ShrtName   -- Signal or Parameter name.
%           unkn_lst   -- Unknown Keyword List generated by NxtrKeyWrdMgr tool.
%
