%  "NxtrReqRprtGen" tool shall generate a Requirements Report as per the FDD authoring specifications.
% 
%  Once invoked "NxtrReqRprtGen" tool shall ask the User to select the correct
%  FDD model for which a Requirements Report needs to be generated.
% 
%  Now this tool will check whether IBM Rational DOORs is running or not and
%  will invoke IBM Rational DOORs if it is not running.
% 
%  If IBM Rational DOORs is already runnning, User need not do anything.
%  If IBM Rational DOORs has been invoked by "NxtrReqRprtGen" tool then User
%  should key-in their DOORs username & password information.
% 
%  Once IBM Rational DOORs application is in running state "NxtrReqRprtGen"
%  shall make all necessary setting changes required for generating a
%  Requirements Report.
% 
%  A detailed Requirements Report shall be generated by "NxtrReqRprtGen" in
%  the current folder.
%
