% This file contains the revision history of Tools folder of our
% tools.
% Current version of tools is "Tools v3.0.0".

hist_TestTools(1).ver = '1.0.0';
hist_TestTools(1).log = 'Initial Release';
hist_TestTools(1).date = '10-July-2015';

hist_TestTools(2).ver = '1.1.0';
hist_TestTools(2).log = 'Fix of infinite loop bug and code cleanup';
hist_TestTools(2).date = '17-July-2015';

hist_TestTools(3).ver = '1.2.0';
hist_TestTools(3).log = ['1) CreateDD --> Updated DD Header to include Synergy Version, Date Modified, Derived by information.'...
                         '2) VerifyDD --> Added checks to support the new entries of .TuningOwner property in Calibration Data class.'...
						 '3) MIL --> Updated History file name.'...
						 '4) SaveSimData --> Forced an internal variable to be of type double.'];
hist_TestTools(3).date = '05-Aug-2015';

hist_TestTools(4).ver = '1.3.0';
hist_TestTools(4).log = ['1) Keyword Check: Added logic to exclude known signals that shall never follow Nexteer EPS naming conventions.'...
                         '2) NxtrReqRprtGen --> New tool to automatically generate Requirements Report based on FDD authoring specification.'...
						 '3) VerifyDD --> Bug Fix: Updated check related to usage of FDD Name in Global Config Parameters.'...
                         '4) VerifyDD --> Updated logic to differentiate a DataDict.Constant & DataDict.ConfigParam parameters.'...
						 '5) MIL --> Added logic to check Test Definition files for errors before initiating MIL validation.'];
hist_TestTools(4).date = '20-Aug-2015';

hist_TestTools(5).ver = '1.4.0';
hist_TestTools(5).log = ['1) Keyword Check: Added logic to exclude known names used for NVM client/Server that shall never follow EPS naming conventions.'...
                         '2) VerifyDD --> Added logic to check each NVM client has a corresponding NVM entry in the same DD.'];
hist_TestTools(5).date = '01-Sept-2015';

hist_TestTools(5).ver = '1.5.0';
hist_TestTools(5).log = ['1) CreateDD --> Added logic to parse Data Dictionary entries if the their description attribute contains "%" symbol in it.'...
                         '2) MIL --> Added logic to automatically close Coverage report after simulation.'];
hist_TestTools(5).date = '24-Sept-2015';

hist_TestTools(6).ver = '1.6.0';
hist_TestTools(6).log = ['1) VerifyDD --> Updated examples so that users can get rid of errors in Data Dictionary files easily.'...
                         '2) VerifyDD --> Improved naming conventions checks for Server Runnables in EA4.'...
						 '3) VerifyDD --> Updated Calibration.GraphLink property check as per the latest tools(Data_Management v2.22.0).'...
                         '4) MIL --> Type casted an internal variable to support Enumerations during MIL Validation.'];
hist_TestTools(6).date = '15-Oct-2015';

hist_TestTools(7).ver = '1.7.0';
hist_TestTools(7).log = ['1) MIL --> Added functionality to modify Imported Calibrations during MIL validation.'...
                         '2) MIL --> Added functionality to fix chopping of signal names from the top level Test Harness model during MIL validation.'...
                         '3) MIL --> Added functionality to support FDD models that have only Server runnables and no Input & Output signals for periodic runnables.'];
hist_TestTools(7).date = '21-Oct-2015';

hist_TestTools(8).ver = '1.8.0';
hist_TestTools(8).log = '1) MIL --> Bug fix: Imported cal updated in previous version was breaking execution as imported cal was expected to be part of parameter definition file all the time. In this version, it is fixed to handle imported cal separately.';
hist_TestTools(8).date = '26-Oct-2015';

hist_TestTools(9).ver = '1.9.0';
hist_TestTools(9).log = ['1) VerifyDD --> Complete re-write of tool to make it maintenance-free.'...
                         '2) VerifyDD --> Updated checks to ensure FDD name is correctly used in Data Dictionary files.'...
                         '3) VerifyDD --> Added new checks to ensure same set of Runnables & Server Runnables are used in Model & Data Dictionary.'...
						 '4) VerifyDD --> Added new checks to ensure that "StateMustResolveToSignalObject" property is enabled for Unit Delay & Data Store Memory blocks.'...
						 '5) VerifyDD --> Added logic to exclude Registry signals from EA4 master Signal list.'...
						 '6) MIL --> Added logic to support DDs with multiple SrvRunnable objects.'];
hist_TestTools(9).date = '04-Nov-2015';

hist_TestTools(10).ver = '1.10.0';
hist_TestTools(10).log = ['1) VerifyDD --> Updated logic to allow FDDs with numbers in FDD ShoNames.'...
                         '2) VerifyDD --> Updated logic to correctly place NTC signal violations in generated VerifyDD report.'...
                         '3) VerifyDD --> Updated logic to ensure that Data Store Memory blocks are checked only for NVM, PIM & Display signals.'...
						 '4) MIL --> Optimized logic to parse Data Dictionary files used for MIL Validation.'];
hist_TestTools(10).date = '21-Dec-2015';

hist_TestTools(10).ver = '1.11.0';
hist_TestTools(10).log = ['1) VerifyDD --> Added logic to check Description property for all Data classes.'...
                         '2) VerifyDD --> Removed all kinds of checks related to .Header property under Constant & ConfigParam Data Class.'...
                         '3) VerifyDD --> Removed all kinds of checks related to .Dependencies property under FDD data class.'...
						 '4) VerifyDD --> Added new checks to Runnable Data Class.'...
						 '5) SaveSimData --> Now using dlmwrite to create csv file instead of csvwrite.'];
hist_TestTools(10).date = '15-Apr-2016';


hist_TestTools(12).ver = '1.12.0';
hist_TestTools(12).log = ['1) CreateDD --> Removed Date Modified tag from DD Header.'...
                         '2) MakeTestCals --> Added logic to generate Imported Calibrations in Test Plan Parameter files.'...
                         '3) MIL --> Added logic to check for Non-numerical sample-time used in UTP Harness model.'];
hist_TestTools(12).date = '29-Apr-2016';


hist_TestTools(13).ver = '1.13.0';
hist_TestTools(13).log = '1) VerifyDD --> Added logic to check .TestTolerance property for CSArguments Data Class.';
hist_TestTools(13).date = '02-Jun-2016';


hist_TestTools(14).ver = '1.14.0';
hist_TestTools(14).log = '1) MIL --> Updated list of library blocks to be excluded from Model Coverage.';
hist_TestTools(14).date = '07-Jul-2016';


hist_TestTools(15).ver = '1.15.0';
hist_TestTools(15).log = '1) MIL --> Added logic to verify UTP Harness model before initiating MIL process.';
hist_TestTools(15).date = '15-Jul-2016';

hist_TestTools(16).ver = '1.16.0';
hist_TestTools(16).log = ['1) MIL --> Updated logic to check Test Definition files for errors before initiating MIL validation.'...
                          '2) MIL --> Added functionality to support Multi-dimensional signals.'...
                          '3) MIL --> Test Vector information shall be saved in a .xlsx format instead of .csv format to support multi-dimensional signals.'];
hist_TestTools(16).date = '12-Sep-2016';

hist_TestTools(17).ver = '1.17.0';
hist_TestTools(17).log = ['1) CreateDD --> Added support for Development Data Dictionaries.'...
                          '2) VerifyDD --> Added support for Development Data Dictionaries.'...
						  '3) VerifyDD --> Added logic to indetify usage of EA3 structures and Enumerations in EA4 program and vice-versa.'...
                          '4) MIL --> Robustified checks to parse Test Definition file.'];
hist_TestTools(17).date = '19-Sep-2016';

hist_TestTools(18).ver = '2.0.0';
hist_TestTools(18).log = ['1) STool --> New Integrated Simulation platform tool for developing EPS functions.'...
                          '2) VerifyDD --> Added new check to verify .Mnemonic case sensitivity for EA3 programs.'];
hist_TestTools(18).date = '19-Oct-2016';


hist_TestTools(19).ver = '2.1.0';
hist_TestTools(19).log = ['1) MakeTestCals --> Added Min & Max values as comments for each calibration.'...
                          '2) MIL --> Robustified functionality to support multi-dimensional signals.'...
						  '3) MIL --> Updated logic to ensure proper usage of Imported calibrations during MIL validation.'];
hist_TestTools(19).date = '15-Nov-2016';


hist_TestTools(20).ver = '2.2.0';
hist_TestTools(20).log = '1) MIL --> Minor bug fix to support multi-dimensional array signals.';
hist_TestTools(20).date = '20-Nov-2016';

hist_TestTools(20).ver = '2.3.0';
hist_TestTools(20).log = ['1) MIL --> Added support to generate Verification reports automatically for EA4 programs.'...
                          '2) MIL --> Updated logic to ensure proper usage of Imported calibrations during MIL validation.'...
                          '3) STool --> Design Package: MATLAB will exit automatically to release all network licenses.'...
                          '4) STool --> Design Package: Data Dictionary shall be generated again during Design package creation.'...
                          '5) STOol --> Design Package: Requirements report zip file has been renamed as "<FDD Number>_<FDD ShortName>_Requirements_Report.zip" to avoid conflicts with older version of reports in synergy.'...
                          '6) VerifyDD --> Updated Mnemonic check for Imported calibration.'...
                          '7) VerifyDD --> Turned off checks to allow usage of component short name at the begining of Signal names and added a checklist item for manual verification.'...
                          '8) VerifyDD --> Excluded known special cases from being reported as errors from the report for Constants & Config Params.'];
hist_TestTools(20).date = '03-Apr-2017';

hist_TestTools(21).ver = '2.4.0';
hist_TestTools(21).log = ['1) STool --> MIL: Added logic to automatically generate Peer Review checklists for MIL.'...
                          '2) STool --> Added new tools to search AUTOSAR keywords, EA4 signal names, EA3 signal names.'...
                          '3) STool --> Design Package: Bug fix to generate Model Advisor report using a SetupSim file when available.'...
                          '4) STool --> Design Package: Added logic to automatically generate Peer review checklists for Design.'...
                          '5) MakeTestCals --> Added logic to generate Config Params in Test Plan Parameter files.'...
                          '6) STool --> MIL: Updated logic to not override the calibration values when they are out of range.'...
                          '7) STool --> MIL: Updated logic to vary Config Params during MIL validation.'...
                          '8) STool --> MIL: Turned off MIL status messages to command prompt.'];
hist_TestTools(21).date = '27-Apr-2017';

hist_TestTools(22).ver = '2.5.0';
hist_TestTools(22).log = '1) STool --> MIL: Added functionilty to generate Inspection report with more information automatically.';
hist_TestTools(22).date = '24-May-2017';

hist_TestTools(23).ver = '3.0.0';
hist_TestTools(23).log = ['1) CreateDD --> Added functionilty to generate Runnables/Server Runnables for EA3 programs.'...
						  '2) STool --> All tools have been updated to support Runnable/Server Runnable concept for EA3 programs.'...
						  '3) VerifyDD --> Added functionality to check Runnables/Server Runnables & Client Runnables for EA3 programs.'...
						  '4) VerifyDD --> Added check to notify user if there are unsaved changes in the model.'];
hist_TestTools(23).date = '16-Jun-2017';

